### ISSUE TITLE
Undefined index "environment" in Receipts/ReceiptResponse.php

### ISSUE THREAD

**Issue by the-solfegio** [imdhemy/appstore-iap#4]
Hi, @imdhemy - first of all - thanks for the thoughtful work You had done - code is of high quality in all of the packages, designed for managing mobile in-app purchases!

However, when attempting to verify a auto-renewable subscription receipt against sandbox account, we stumbled upon PHP Notice:
`PHP Notice:  Undefined index: environment in vendor/imdhemy/appstore-iap/src/Receipts/ReceiptResponse.php on line 58`

(using version `0.3.2`, revision: `7ebc49c42b1fcd6b1885e7064f3aad15de731160`)

Examining payload, returned by Apple server, it looks like there are no `"environment"` key present (receipt as obtained using a sandbox account on iPhone, which was connected via cable to host, using a locally built application (as opposed to one, installed from TestFlight)

Please, let me know if any other details could help, and looking forward to a resolution,
Artūrs

**Comment by the-solfegio** [comment]
For testing, I used `laravel/tinker` REPL, and issued the following code:
```php
$httpClient = \Imdhemy\AppStore\ClientFactory::create($sandbox = true);
$pw = env("APPSTORE_IAP_SECRET", "");
$verifier = new \Imdhemy\AppStore\Receipts\Verifier($httpClient, "...receipt-we-obtained-from-app...", $pw);
$result = $verifier->verifyRenewable();
```

**Comment by the-solfegio** [comment]
Another problem (while verifying a first receipt, obtained by subscribing to our auto-renewable product), was in the same file, in lines 62.-65:
```php
        $this->latestReceiptInfo = [];
        foreach ($attributes['latest_receipt_info'] as $itemAttributes) {
            $this->latestReceiptInfo[] = ReceiptInfo::fromArray($itemAttributes);
        }
```

Desipte an array being expected, we received a flat JSON object in the following form:
```json
  "latest_receipt_info": {
    "original_purchase_date_pst": "2020-12-22 08:27:15 America/Los_Angeles",
    "quantity": "1",
    ...
    },
   ...
```

**Comment by the-solfegio** [comment]
Received JSON object had the following contents:
```json
{
  "receipt": {
    "original_purchase_date_pst": "2020-12-22 08:27:15 America/Los_Angeles",
    "quantity": "1",
    "unique_vendor_identifier": "...-...-...-...-............",
    "bvrs": "48",
    "expires_date_formatted": "2020-12-23 17:54:04 Etc/GMT",
    "is_in_intro_offer_period": "false",
    "purchase_date_ms": "1608745744922",
    "expires_date_formatted_pst": "2020-12-23 09:54:04 America/Los_Angeles",
    "is_trial_period": "false",
    "item_id": "1545669289",
    "unique_identifier": "...hashed...",
    "original_transaction_id": "1000000........",
    "subscription_group_identifier": "20...",
    "transaction_id": "1000000........",
    "web_order_line_item_id": "10000000........",
    "version_external_identifier": "0",
    "purchase_date": "2020-12-23 17:49:04 Etc/GMT",
    "product_id": "individual.subscription.monthly",
    "expires_date": "1608746044922",
    "original_purchase_date": "2020-12-22 16:27:15 Etc/GMT",
    "purchase_date_pst": "2020-12-23 09:49:04 America/Los_Angeles",
    "bid": "our.app.id",
    "original_purchase_date_ms": "1608654435000"
  },
  "auto_renew_product_id": "individual.subscription.monthly",
  "auto_renew_status": 1,
  "latest_receipt_info": {
    "original_purchase_date_pst": "2020-12-22 08:27:15 America/Los_Angeles",
    "quantity": "1",
    "unique_vendor_identifier": "...-...-...-...-............",
    "bvrs": "48",
    "expires_date_formatted": "2020-12-29 15:34:04 Etc/GMT",
    "is_in_intro_offer_period": "false",
    "purchase_date_ms": "1609252444000",
    "expires_date_formatted_pst": "2020-12-29 07:34:04 America/Los_Angeles",
    "is_trial_period": "false",
    "item_id": "1545673007",
    "unique_identifier": "bb....................................",
    "original_transaction_id": "1000000.........",
    "subscription_group_identifier": "20......",
    "transaction_id": "1000000.........",
    "bid": "our.app.id",
    "web_order_line_item_id": "10000000........",
    "purchase_date": "2020-12-29 14:34:04 Etc/GMT",
    "product_id": "individual.subscription.monthly",
    "expires_date": "1609256044000",
    "original_purchase_date": "2020-12-22 16:27:15 Etc/GMT",
    "purchase_date_pst": "2020-12-29 06:34:04 America/Los_Angeles",
    "original_purchase_date_ms": "1608654435000"
  },
  "latest_receipt": "....",
  "status": 0
}
```

**Comment by imdhemy** [comment]
Hi Artūrs @the-solfegio,
Thank you for your nice words! ❤️ I'm really happy to read this.

**Concerning the PHP Notice of `Undefined index: environment`**, [[1]](https://github.com/imdhemy/appstore-iap/issues/4#issue-775937889) , [[2]](https://github.com/imdhemy/appstore-iap/issues/4#issuecomment-752112389)

- Apple suggests as a best practice, always call the production URL for `verifyReceipt` first, and proceed to verify with the sandbox URL if you receive a `21007` status code. (`Imdhemy\AppStore\ValueObjects\Status`). 
- Be sure that the `receiptData` value is a valid, well-formatted Base64-encoded receipt data.


**Concerning the `latestReceiptInfo`** [[3]](https://github.com/imdhemy/appstore-iap/issues/4#issuecomment-752113864), [[4]](https://github.com/imdhemy/appstore-iap/issues/4#issuecomment-752116130), I just tested the first receipt of a fresh account, the `latest_receipt_info` key was returned as array:
```
 "latest_receipt_info" => array:1 [
    0 => array:17 [
      "quantity" => "1"
      "product_id" => "month_premium"
      "transaction_id" => "1000000........"
      "original_transaction_id" => "1000000........."
	...
]
```
Below is a quote from the [App store official documentation](https://developer.apple.com/documentation/appstorereceipts/responsebody): 

> latest_receipt_info
> [responseBody.Latest_receipt_info]
> An array that contains all in-app purchase transactions. This excludes transactions for consumable products that have been marked as finished by your app. Only returned for receipts that contain auto-renewable subscriptions.

Since I couldn't reproduce the issue, I'm open to conduct a screen meeting with you to debug this issue together. You can find my email [here](https://github.com/imdhemy/appstore-iap/blob/main/composer.json#L7).

Dhemy

**Comment by imdhemy** [comment]
Hi, @the-solfegio

`Undefined index: environment` Error is due to a receipt is from the test environment, but it was sent to the production environment for verification.

This is handled now in version `0.3.3`. When the error status code [21007] is returned, a new verification request is sent to the sandbox URL to verify the receipt.

I hope you found a solution to the other mentioned problem!

Cheers,
Dhemy

**Comment by mreall** [comment]
Hi @imdhemy, I'm having the same issues that @the-solfegio mentions above. I'm using version 0.3.11. Sometimes the `environment` variable appears as an undefined index and `latest_receipt_info` is an associative array instead of an array of associative arrays. Both of these issues happen when validating a transaction, in other words, if there is no `environment` index, the `latest_receipt_info` is an associative array.

Do you know why this is happening? Or, does it make sense to convert `latest_receipt_info` to an array of associative arrays before the `foreach` loop in this scenario?

**Comment by imdhemy** [comment]
Hi @mreall 

Could you provide me the received response on the mentioned use cases, please?

For instance:
When using the following snippet:
```php
$response = $foo->getBar();

```
I receive the following response
```javascript
{
	"key": "value",
	"another": "one",
}
```

Or we can have a call to debug this together. You can find my email on the `composer.json` file.

**Comment by mreall** [comment]
@imdhemy, thanks for the quick response. 

I send the full transaction from the app to my Laravel controller where I call the following:
```
use Imdhemy\Purchases\Facades\Subscription as appSubscription;
...
$receiptData = $request->transaction['transactionReceipt'];
$receiptResponse = appSubscription::appStore()->receiptData($receiptData)->verifyRenewable();
```

Very similar to what @the-solfegio posted, after the App Store responds, `ReceiptResponse::__construct()` is called with the following as the `$attributes` parameter:
```
{
    "receipt": {
      "original_purchase_date_pst": "2021-08-04 11:32:02 America/Los_Angeles",
      "quantity": "1",
      "unique_vendor_identifier": "...",
      "bvrs": "41",
      "expires_date_formatted": "2021-08-12 21:46:56 Etc/GMT",
      "is_in_intro_offer_period": "false",
      "purchase_date_ms": "1628804516000",
      "expires_date_formatted_pst": "2021-08-12 14:46:56 America/Los_Angeles",
      "is_trial_period": "false",
      "item_id": "1577804120",
      "unique_identifier": "...",
      "original_transaction_id": "100000085381----",
      "subscription_group_identifier": "2085----",
      "transaction_id": "100000085856----",
      "in_app_ownership_type": "PURCHASED",
      "web_order_line_item_id": "100000006493----",
      "purchase_date": "2021-08-12 21:41:56 Etc/GMT",
      "product_id": "test_product",
      "expires_date": "1628804816000",
      "original_purchase_date": "2021-08-04 18:32:02 Etc/GMT",
      "purchase_date_pst": "2021-08-12 14:41:56 America/Los_Angeles",
      "bid": "...",
      "original_purchase_date_ms": "1628101922000"
    },
    "auto_renew_product_id": "test_product",
    "auto_renew_status": 1,
    "latest_receipt_info": {
      "original_purchase_date_pst": "2021-08-04 11:32:02 America/Los_Angeles",
      "quantity": "1",
      "unique_vendor_identifier": "...",
      "bvrs": "41",
      "expires_date_formatted": "2021-08-12 21:46:56 Etc/GMT",
      "is_in_intro_offer_period": "false",
      "purchase_date_ms": "1628804516000",
      "expires_date_formatted_pst": "2021-08-12 14:46:56 America/Los_Angeles",
      "is_trial_period": "false",
      "item_id": "1577804120",
      "unique_identifier": "...",
      "original_transaction_id": "100000085381----",
      "subscription_group_identifier": "2085----",
      "transaction_id": "100000085856----",
      "in_app_ownership_type": "PURCHASED",
      "web_order_line_item_id": "100000006493----",
      "purchase_date": "2021-08-12 21:41:56 Etc/GMT",
      "product_id": "test_product",
      "expires_date": "1628804816000",
      "original_purchase_date": "2021-08-04 18:32:02 Etc/GMT",
      "purchase_date_pst": "2021-08-12 14:41:56 America/Los_Angeles",
      "bid": "...",
      "original_purchase_date_ms": "1628101922000"
    },
    "latest_receipt": "...",
    "status": 0
  }
```

An exception is thrown because `$attributes['environment']` doesn't exist. If I change the code to:
```
$this->environment = $attributes['environment'] ?? null;
```

then I still get an exception from the following code because `ReceiptInfo::fromArray()` is expecting `$itemAttributes` to be an array, but receives a string.
```
foreach ($attributes['latest_receipt_info'] ?? [] as $itemAttributes) {
   $this->latestReceiptInfo[] = ReceiptInfo::fromArray($itemAttributes);
}
```

Does that help?

**Comment by mreall** [comment]
I can't find any documentation from Apple that explains the differences in the format of the "Already purchased" verifyReceipt object from a regular verifyReceipt object. But the `receipt` value that gets returned also doesn't include all the data listed in the [receipt spec](https://developer.apple.com/documentation/appstorereceipts/responsebody/receipt), either. For example, `adam_id`, `app_item_id` and several other values are missing.

Perhaps an exception should be thrown if `$attributes['environment']` doesn't exist. Then each developer can determine how we handle it (in my case I'd simply catch and ignore the exception as the purchase has already been processed).

**Comment by imdhemy** [comment]
@mreall Thanks for further investigation. Currently, I'm working on a new release, and I'll consider this issue for sure.
